# Generated by Django 4.0.2 on 2022-02-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0002_properties_alter_customer_buying_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='details',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
