# Generated by Django 4.0.2 on 2022-02-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0003_alter_properties_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
    ]
